### ISSUE TITLE
Creation of ConceptDescription via ECLASS XML makes PE3 refusing to save the aasx-File

### ISSUE THREAD

**Issue by foprs** [eclipse-aaspe/aaspe#156]
I used 
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/118162568/b6bc4721-0dbe-4475-9da7-f8ce9efc1b09)
to generate a ConceptDescription via Create <- ECLASS .

After selecting the Property
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/118162568/4385a855-89a8-4235-b843-bbf9b7a27ebe)

PE 3 jumps back to the editor window. The ConceptDesription has not been created.

PE 3 refuses to save the file and the work done so far get's lost.

Error message:
Error: when saving AASX: PackageCentral: while saving local file: C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasx buffered to: C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx with new filename C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasxat \PackageContainerLocalFile.cs:line 202 gave: While indirect-saving aasx to source local file: C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasx buffered to: C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx at \AdminShellPackageEnv.cs:line 1060 gave: The process cannot access the file 'C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx' because it is being used by another process. PackageCentral: while saving local file: C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasx buffered to: C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx with new filename C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasxat \PackageContainerLocalFile.cs:line 202 gave: While indirect-saving aasx to source local file: C:\Users\ricos\OneDrive - FoP Consult GmbH (1)\(200) Projekte\(140) InterOpera\110 Technical_Data_for_AGV_in_Intralogistics (02056)\100 Modellierung\AGV_v3.aasx buffered to: C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx at \AdminShellPackageEnv.cs:line 1060 gave: The process cannot access the file 'C:\Users\ricos\AppData\Local\Temp\tmp2C0E.aasx' because it is being used by another process. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.SaveAsAsync(String saveAsNewFileName, SerializationFormat prefFmt, PackCntRuntimeOptions runtimeOptions, Boolean doNotRememberLocation) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 174
   at AasxPackageLogic.MainWindowAnyUiDialogs.CommandBinding_GeneralDispatchAnyUiDialogs(String cmd, AasxMenuItemBase menuItem, AasxMenuActionTicket ticket) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\MainWindowAnyUiDialogs.cs:line 294.

**Comment by quickhdsdcIPA** [comment]
I have a similar problem when try to import an ECLASS concept description. Belowe is the error message

Error: when expanding all visual AASX elements: Object reference not set to an instance of an object. Object reference not set to an instance of an object. at    at Extensions.ExtendLangString.GetDefaultStringGen[T](List`1 langStrings, String defaultLang) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\Extensions\ExtendLangString.cs:line 31
   at Extensions.ExtendILangStringPreferredNameTypeIec61360.GetDefaultString(List`1 langStringSet, String defaultLang) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\Extensions\ExtendILangStringPreferredNameTypeIec61360.cs:line 23
   at AasxPackageLogic.VisualElementConceptDescription.RefreshFromMainData() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\VisualAasxElements.cs:line 1224
   at AasxPackageLogic.VisualElementConceptDescription..ctor(VisualElementGeneric parent, TreeViewLineCache cache, Environment env, IConceptDescription cd) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\VisualAasxElements.cs:line 1198
   at AasxPackageLogic.ListOfVisualElement.GenerateVisualElementsForSingleCD(TreeViewLineCache cache, Environment env, IConceptDescription cd, VisualElementGeneric parent) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\VisualAasxElements.cs:line 1562
   at AasxPackageLogic.ListOfVisualElement.GenerateInnerElementsForConceptDescriptions(TreeViewLineCache cache, Environment env, VisualElementEnvironmentItem tiCDs, VisualElementGeneric root, Boolean doSort) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\VisualAasxElements.cs:line 1889
   at AasxPackageLogic.ListOfVisualElement.ExecuteLazyLoading(VisualElementGeneric ve, Boolean forceExpanded) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\VisualAasxElements.cs:line 2154
   at AasxPackageExplorer.DiplayVisualAasxElements.ExpandAllItems() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxWpfControlLibrary\DiplayVisualAasxElements.xaml.cs:line 944.
