### ISSUE TITLE
NullReferenceException in nameplate viewer DN2

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#25]
**Describe the bug**
I wan to create a digital nameplate with the help of digital nameplate viewers.

**To Reproduce**
1. Create a new AAS
2. At the AAS, click "Create new submodel of kind instance"
3. Click "Create data element" for *semanticId*
4. Choose ModelReference
5. Click "Add blank"
6. Choose Submodel
7. Enter `https://admin-shell.io/zvei/nameplate/1/0/Nameplate`
8. Save the AASX file. This will trigger the display of the nameplate viewers.
9. Click on the viewer DN2
10. An exception happens. The viewer displays nothing.

Log:
```
Error: render AnyUI based visual extension for plugin AasxPluginDigitalNameplate: 
Exception has been thrown by the target of an invocation. 
Exception has been thrown by the target of an invocation.
InnerException: Object reference not set to an instance of an object. at
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at AasxPackageLogic.Plugins.PluginInstance.InvokeAction(String name, Object[] args) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\Plugins.cs:line 128
   at AasxPackageExplorer.DispEditAasxEntity.DisplayOrEditVisualAasxElement(PackageCentral packages, AnyUiDisplayContextWpf displayContext, ListOfVisualElementBasic entities, Boolean editMode, Boolean hintMode, Boolean showIriMode, Nullable`1 cdSortOrder, IFlyoutProvider flyoutProvider, IPushApplicationEvent appEventProvider, HighlightFieldInfo hightlightField, AasxMenu superMenu) 
in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxWpfControlLibrary\DispEditAasxEntity.xaml.cs:line 534.Inner message: Object reference not set to an instance of an object.
```
**Expected behavior**
No exception.
The nameplate viewer displays an empty nameplate.

**Screenshots**
![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/610920cd-cb48-4f46-8451-f06aee80aecf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A

**Smartphone (please complete the following information):**
None

**Additional context**
Version 2023-11-17

**Comment by juileetikekar** [comment]
Hi @WelliSolutions,

Thank you for raising the issue!!

The issue was reproduced. We will provide you further updates.
