### ISSUE TITLE
Exception while loadin an aas from aasx-server

### ISSUE THREAD

**Issue by martafullen** [eclipse-aaspe/aaspe#38]
**Describe the bug**

Some aasx packages cannot be read from the aasx-server.

Trace:
```
System.Exception
  HResult=0x80131500
  Message=While reading the AASX 00_HMI22_VDMA_AAS_WEISS_HN.aasx at \AdminShellPackageEnv.cs:line 455 gave: While reading spec from the AASX 00_HMI22_VDMA_AAS_WEISS_HN.aasx at \xmlization.cs:line 20625 gave: The required property Keys has not been given in the XML representation of an instance of class Reference at: assetAdministrationShells/*[0]/derivedFrom
  Source=AasxCsharpLibrary
  StackTrace:
   at AdminShellNS.AdminShellPackageEnv.LoadPackageAasx(String fn, String fnToLoad) \eclipse-aaspe\aaspe\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 465
   at AdminShellNS.AdminShellPackageEnv.Load(String fn, Boolean indirectLoadSave) \eclipse-aaspe\aaspe\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 524
   at AdminShellNS.AdminShellPackageEnv..ctor(String fn, Boolean indirectLoadSave) \eclipse-aaspe\aaspe\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 274
   at AasxPackageLogic.PackageCentral.AasxFileServerInterface.PackageContainerAasxFileRepository.<LoadAasxFileFromServer>d__13.MoveNext() in \eclipse-aaspe\aaspe\src\AasxPackageLogic\PackageCentral\AasxFileServerInterface\PackageContainerAasxFileRepository.cs:line 74
   at AasxPackageExplorer.MainWindow.<<Window_Loaded>b__58_1>d.MoveNext() in \eclipse-aaspe\aaspe\src\AasxPackageExplorer\MainWindow.xaml.cs:line 928
```

**To Reproduce**
1. Debug Package Explorer from eclipse-aaspe/aaspe/main
2. Connect to AASX repository at https://v3.admin-shell-io.com/api
3. Read a file from the server; some load, some raise the above exception

**Expected behavior**
All files loading

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 11
 - Version: aaspe/main

**Additional context**
Unlike in https://github.com/eclipse-aaspe/aaspe/issues/37, the packages don't crash aasx-server

**Comment by juileetikekar** [comment]
Hi @martafullen,

Thank you for raising the issue!

In my opinion, the issue might be in both AASX Server and AASPE. Could you please confirm if these erred files are V1 oe V2 files? Is it possible to share the erred files, i.e., original V1/V2 files for further inverstigation?
